name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-analyze-and-push:
    name: Build, Test, Analyze, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out a copy of your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Sets up the Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Runs your unit tests
      - name: Run Unit Tests with Maven
        run: mvn -B test

      # 4. Runs the SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Example: swetasuman295/portfolio-backend:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest