name: Build and Push

on:
  push:
    branches: [main]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Push Backend
        run: |
          docker build -t swetasuman295/portfolio-backend:latest ./portfolio-backend
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push swetasuman295/portfolio-backend:latest
  
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Push Frontend
        run: |
          docker build -t swetasuman295/portfolio-frontend:latest ./sweta-suman-portfolio
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push swetasuman295/portfolio-frontend:latest